name: finrem-emca
home: https://github.com/hmcts/finrem-evidence-management-client-api
version: 0.0.1
description: Financial Remedy Evidence Management API
maintainers:
  - name: HMCTS Financial Remedy Team
