java:
  aadIdentityName: finrem
  ingressHost: "finrem-emca-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
  applicationPort: '4006'
  image: 'https://hmcts.azurecr.io/hmcts/finrem-evidence-management-client-api:latest'
  keyVaults:
    finrem:
      secrets:
        - idam-secret
        - finrem-doc-s2s-auth-secret

